<?php
/* Start EN Language Pack */

$DatabaseNotFound = "Database File Not Found";
$Footer = "Website create by the <a href=\"http://sths.simont.info\">SimonT Hockey Simulator (STHS)</a> for ";
$WarningResolution = "Your browser screen resolution is too small for this page. Some information are hidden to keep the page readable.";

$TableSorterLang = array(
'ShoworHideColumn'		=> 'Show or Hide Column',
'ResetAllSearchFilter'		=> 'Reset All Search Filter',
'FilterTips'			=> 'Filter Tips',
'Search'			=> 'Search',
);

$TransactionLang = array(
'LeagueTitle'		=> 'League Transactions',
'TeamTitle'			=> 'Transactions for ',
'TradeHistory'			=> 'Trade History',
);

$WaiverLang  = array(
'Title'		=> 'Waivers',
'Waiver'		=> 'Waivers',
'PlayerName'			=> 'Player Name (Overall)',
'FromTeam'			=> 'From Team',
'Pickedby'			=> 'Picked by',
'DayPutonWaivers'			=> 'Day Put on Waivers',
'DayRemovedfromWaivers'			=> 'Day Removed from Waivers',
'WaiverOrder'		=> 'Waiver Order',
);

$CoachesLang = array(
'CoachesTitle'		=> 'Coaches',
'ProCoaches'			=> 'Pro Coaches',
'FarmCoaches'			=> 'Farm Coaches',
'AvailableCoaches'			=> 'Available Coaches',
'CoachesName'			=> 'Coaches Name',
'TeamName'			=> 'Team Name',
'Age'			=> 'Age',
'Salary'			=> 'Salary',
'Contract'			=> 'Contract',
);

$ScheduleLang = array(
'ScheduleTitle1'		=> 'League ',
'ScheduleTitle2'		=> ' Schedule',
'TeamTitle'			=> ' Schedule for ',
'Day'			=> 'Day',
'Game'			=> 'Game',
'VisitorTeam'			=> 'Visitor Team',
'HomeTeam'			=> 'Home Team',
'Score'			=> 'Score',
'Link'			=> 'Link',
'BoxScore'			=> 'BoxScore',
);

$SearchLang = array(
'SearchTitle'		=> 'Search',
'Team'		=> 'Team:',
'AllTeam'		=> 'All Team',
'Type'		=> 'Type:',
'ProandFarm'		=> 'Pro and Farm',
'ProOnly'		=> 'Pro Only',
'FarmOnly'		=> 'Farm Only',
'OrderField'		=> 'Order Field:',
'Max'		=> 'Max:',
'FreeAgents'		=> 'Free Agents:',
'ThisYear'		=> 'This Year',
'NextYear'		=> 'Next Year',
'In2Years'		=> 'In 2 Years',
'In3Years'		=> 'In 3 Years',
'In4Years'		=> 'In 4 Years',
'In5Years'		=> 'In 5 Years',
'Unlimited'		=> '0 - Unlimited',
'AcsendingOrder'		=> 'Acsending Order:',
'DecendingOrder'		=> 'Decending Order:',
'Select'		=> 'Select',
'Farm'		=> 'Farm:',
'PlayersRosterMenu'		=> 'Players Roster Menu',
'GoaliesRosterMenu'		=> 'Goalies Roster Menu',
'PlayersInformationMenu'		=> 'Players Information Menu',
'PlayersStatsMenu'		=> 'Players Stats Menu',
'GoaliesStatsMenu'		=> 'Goalies Stats Menu',
'TeamStatsMenu'		=> 'Team Stats Menu',
);

$PlayersLang = array(
'PlayerName'		=> 'Player Name',
'GoalieName'		=> 'Goalie Name',
'TeamName'			=> 'Team Name',
'Age'			=> 'Age',
'Birthday'			=> 'Birthday',
'Rookie'			=> 'Rookie',
'Weight'			=> 'Weight',
'Height'			=> 'Height',
'NoTrade'			=> 'No Trade',
'ForceWaiver'			=> 'Force  Waivers',
'Status'			=> 'Status',
'Contract'			=> 'Contract',
'Type'			=> 'Type',
'Salary'			=> 'Salary',
'CurrentSalary'			=> 'Current Salary',
'SalaryYear'			=> 'Salary Year',
'SalaryRemaining'			=> 'Salary Remaining',
'SalaryAverage'			=> 'Salary Average',
'SalaryAveRemaining'			=> 'Salary Ave Remaining',
'1WayContract'			=> ' (1 Way Contract)',
'OutofPayroll'			=> ' (Out of Payroll)',
'Link'			=> 'Link',
'UFA'			=> 'UFA',
'RFA'			=> 'RFA',
);

$DynamicTitleLang = array(
'InDecendingOrderBy'		=> ' In Decending Order By ',
'InAscendingOrderBy'			=> ' In Ascending Order By ',
'PlayersInformation'			=> ' Players Information',
'PlayersRoster'			=> ' Players Roster',
'GoaliesRoster'			=> ' Goalies Roster',
'GoaliesStat'			=> ' Goalies Stats',
'PlayersStat'			=> ' Players Stats',
'TeamStat'			=> ' Team Stats',
'TeamStatVS'			=> ' Team Stats VS',
'PlayersInformation'			=> ' Players Information',
'ThisYearFreeAgents'			=> ' This Year Free Agents',
'NextYearFreeAgents'			=> ' Next Year Free Agents',
'YearsFreeAgents'			=> ' Years Free Agents',
'Unassigned'			=> 'Unassigned',
'Pro'			=> ' Pro',
'Farm'			=> ' Farm',
'All'			=> ' All',
'Top'			=> ' Top ',
'IndividualLeadersTitle'		=> 'Individual Leaders',
);

$TeamStatLang = array(
'Overall'		=> 'Overall',
'Home'			=> 'Home',
'Visitor'		=> 'Visitor',
'TeamName'			=> 'Team',
'Last10'		=> 'Last 10',
);

$StandingLang = array(
'Standing'		=> ' Standing',
'Wildcard'		=> 'Wildcard',
'Conference'		=> 'Conference',
'Division'		=> 'Division',
'Overall'		=> 'Overall',
);

$TeamLang = array(
'IncorrectTeam'		=> 'Incorrect Team',
'Teamnotfound'		=> 'Team not found',
'GM'		=> 'GM : ',
'Morale'		=> 'Morale : ',
'TeamOverall'		=> 'Team Overall : ',
'Roster'		=> 'Roster',
'Scoring'		=> 'Scoring',
'PlayersInfo'		=> 'Players Info',
'Lines'		=> 'Lines',
'TeamStats'		=> 'Team Stats',
'Schedule'		=> 'Schedule',
'Finance'		=> 'Finance',
'Depth'		=> 'Depth',
'History'		=> 'History',
'InjurySuspension'		=> 'Injury / Suspension',
'Scratches'		=> 'Scratches',
'TeamAverage'		=> 'TEAM AVERAGE',
'TotalPlayers'		=> 'Total Players',
'AverageAge'		=> 'Average Age',
'AverageWeight'		=> 'Average Weight',
'AverageHeight'		=> 'Average Height',
'AverageContract'		=> 'Average Contract',
'AverageYear1Salary'		=> 'Average Year 1 Salary',
'LineNumber'		=> 'Line #',
'Center'		=> 'Center',
'LeftWing'		=> 'Left Wing',
'RightWing'		=> 'Right Wing',
'Wing'		=> 'Wing',
'Defense'		=> 'Defense',
'Defenseman'		=> 'Defenseman',
'Goalie'		=> 'Goalie',
'TimePCT'		=> 'Time %',
'PHY'		=> 'PHY',
'DF'		=> 'DF',
'OF'		=> 'OF',
'5vs5Forward'		=> '5 vs 5 Forward',
'5vs5Defense'		=> '5 vs 5 Defense',
'PowerPlayForward'		=> 'Power Play Forward',
'PowerPlayDefense'		=> 'Power Play Defense',
'PenaltyKill4PlayersForward'		=> 'Penalty Kill 4 Players Forward',
'PenaltyKill4PlayersDefense'		=> 'Penalty Kill 4 Players Defense',
'PenaltyKill3Players'		=> 'Penalty Kill 3 Players',
'4vs4Forward'		=> '4 vs 4 Forward',
'4vs4Defense'		=> '4 vs 4 Defense',
'LastMinutesOffensive'		=> 'Last Minutes Offensive',
'LastMinutesDefensive'		=> 'Last Minutes Defensive',
'ExtraForwards'		=> 'Extra Forwards',
'ExtraDefensemen'		=> 'Extra Defensemen',
'PenaltyShots'		=> 'Penalty Shots',
'CustomOTLinesForwards'		=> 'Custom OT Lines Forwards',
'CustomOTLinesDefensemen'		=> 'Custom OT Lines Defensemen',
'Normal'		=> 'Normal',
'PowerPlay'		=> 'PowerPlay',
'PenaltyKill'		=> 'Penalty Kill',
'DepthChart'		=> 'Depth Chart',
'Prospects'		=> 'Prospects',
'DraftPicks'		=> 'Draft Picks',
'Year'		=> 'Year',
'ArenaCapacityTicketPriceAttendance'		=> 'Arena Capacity - Ticket Price Attendance - %',
'Level'		=> 'Level',
'Luxury'		=> 'Luxury',
'ArenaCapacity'		=> 'Arena Capacity',
'TicketPrice'		=> 'Ticket Price',
'Attendance'		=> 'Attendance',
'AttendancePCT'		=> 'Attendance PCT',
'Income'		=> 'Income',
'HomeGamesLeft'		=> 'Home Games Left',
'AverageAttendancePCT'		=> 'Average Attendance - %',
'AverageIncomeperGame'		=> 'Average Income per Game',
'YeartoDateRevenue'		=> 'Year to Date Revenue',
'ArenaCapacity'		=> 'Arena Capacity',
'TeamPopularity'		=> 'Team Popularity',
'Expenses'		=> 'Expenses',
'PlayersTotalSalaries'		=> 'Players Total Salaries',
'PlayersTotalAverageSalaries'		=> 'Players Total Average Salaries',
'CoachesSalaries'		=> 'Coaches Salaries',
'SpecialSalaryCapValue'		=> 'Special Salary Cap Value',
'YearToDateExpenses'		=> 'Year To Date Expenses',
'SalaryCapPerDays'		=> 'Salary Cap Per Days',
'SalaryCapToDate'		=> 'Salary Cap To Date',
'LuxuryTaxeTotal'		=> 'Luxury Taxe Total',
'Estimate'		=> 'Estimate',
'EstimatedSeasonRevenue'		=> 'Estimated Season Revenue',
'RemainingSeasonDays'		=> 'Remaining Season Days',
'ExpensesPerDays'		=> 'Expenses Per Days',
'EstimatedSeasonExpenses'		=> 'Estimated Season Expenses',
'TeamTotalEstime'		=> 'Team Total Estime',
'EstimatedSeasonExpenses'		=> 'Estimated Season Expenses',
'EstimatedSeasonSalaryCap'		=> 'Estimated Season Salary Cap',
'CurrentBankAccount'		=> 'Current Bank Account',
'ProjectedBankAccount'		=> 'Projected Bank Account',
'OutFor'		=> ' is out for ',
'Restoftheseason'		=> 'the rest of the season ',
'Days'		=> ' days ',
'1Week'		=> '1 week',
'Weeks'		=> 'weeks',
'1Month'		=> '1 month',
'Months'		=> 'months',
'BecauseofFatigue'		=> ' because of a fatigue.',
'Becauseof'		=> ' because of a ',
'SuspendedIndefinitely'		=> ' is suspended indefinitely.',
'SuspendedFor'		=> ' is suspended for ',
'MoresGames'		=> ' mores games.',
'NoInjuryorSuspension'		=> 'No Injury or Suspension.',
'TotalForPlayers'		=> 'Total For Players',
'AllGames'		=> 'All Games',
'HomeGames'		=> 'Home Games',
'VisitorGames'		=> 'Visitor Games',
'Last10Games'		=> 'Last 10 Games',
'PowerPlayAttemps'		=> 'Power Play Attemps',
'PowerPlayGoals'		=> 'Power Play Goals',
'PowerPlayPCT'		=> 'Power Play %',
'PenaltyKillAttemps'		=> 'Penalty Kill Attemps',
'PenaltyKillGoalsAgainst'		=> 'Penalty Kill Goals Against',
'PenaltyKillPCT'		=> 'Penalty Kill %',
'PenaltyKillPCTGoalsFor'		=> 'Penalty Kill Goals For',
'Shots1Period'		=> 'Shots 1 Period',
'Shots2Period'		=> 'Shots 2 Period',
'Shots3Period'		=> 'Shots 3 Period',
'Shots4Period'		=> 'Shots 4+ Period',
'Goals1Period'		=> 'Goals 1 Period',
'Goals2Period'		=> 'Goals 2 Period',
'Goals3Period'		=> 'Goals 3 Period',
'Goals4Period'		=> 'Goals 4+ Period',
'FaceOffs'		=> 'Face Offs',
'WonOffensifZone'		=> 'Won Offensif Zone',
'TotalOffensif'		=> 'Total Offensif',
'WonOffensifPCT'		=> 'Won Offensif %',
'WonDefensifZone'		=> 'Won Defensif Zone',
'TotalDefensif'		=> 'Total Defensif',
'WonDefensifPCT'		=> 'Won Defensif %',
'WonNeutralZone'		=> 'Won Neutral Zone',
'TotalNeutral'		=> 'Total Neutral',
'WonNeutralPCT'		=> 'Won Neutral %',
'PuckTime'		=> 'Puck Time',
'InOffensifZone'		=> 'In Offensif Zone',
'ControlInOffensifZone'		=> 'Control In Offensif Zone',
'InDefensifZone'		=> 'In Defensif Zone',
'ControlInDefensifZone'		=> 'Control In Defensif Zone',
'InNeutralZone'		=> 'In Neutral Zone',
'ControlInNeutralZone'		=> 'Control In Neutral Zone',
);

$IndexLang = array(
'IndexTitle'		=> 'Index',
'LatestScores' 	=> 'Latest Scores',
'LatestTransactions'		=> 'Latest Trade, Waiver, Injury & Suspension Transactions',
'News'		=> ' News',
'By'		=> ' By',
'On'		=> ' On',
'Top5Point'		=> ' Top 5 Points',
'Top5Goal'		=> ' Top 5 Goals',
'Top5Goalies'		=> ' Top 5 Goalies',
'Top20FreeAgents'		=> 'Top 20 Free Agents',
);

$TodayGamesLang = array(
'TodayGamesTitle'		=> ' Today\'s Games',
'BoxScore'		=> 'BoxScore',
'ProGames'		=> 'Pro Games ',
'FarmGames'		=> 'Farm Games ',
'UnknownGames'		=> 'Unknown Games',
);

$GeneralStatLang = array(
'GamePlayed'		=> 'Game Played',
'Points'		=> 'Points',
'Streak'		=> 'Streak',
'Goals'		=> 'Goals',
'Assists'		=> 'Assists',
'ShotsFor'		=> 'Shots For',
'ShotsAgainst'		=> 'Shots Against',
'ShotsBlock'		=> 'Shots Blocked',
'PenaltyMinutes'		=> 'Penalty Minutes',
'Hits'		=> 'Hits',
'EmptyNetGoals'		=> 'Empty Net Goals',
'Shutouts'		=> 'Shutouts',
'Shots'		=> 'Shots',
'ShotsPCT'		=> 'Shots %',
'Pointper20Minutes'		=> 'Point per 20 Minutes',
'FaceoffPCT'		=> 'Face-off %',
'PlusMinus'		=> 'Plus/Minus',
'Rookie'		=> 'Rookie',
'PowerPlayGoals'		=> 'Power Play Goals',
'ShortHandedGoals'		=> 'Short Handed Goals',
'GameWinningGoals'		=> 'Game Winning Goals',
'GameTyingGoals'		=> 'Game Tying Goals',
'MinutesPlayed'		=> 'Minutes Played',
'HatTricks'		=> 'Hat Tricks',
'GoalsScoringStreak'		=> 'Goals Scoring Streak',
'PointsScoringStreak'		=> 'Points Scoring Streak',
'HitsReceived'		=> 'Hits Received',
'PenaltyShotsGoals'		=> 'Penalty Shots Goals',
'GiveAways'		=> 'Give Aways',
'TakeAways'		=> 'Take Aways',
'TotalFight'		=> 'Total Fight',
'FightWon'		=> 'Fight Won',
'SavePCT'		=> 'Save Percentage',
'GoalsAgainstAverage'		=> 'Goals Against Average',
'Wins'		=> 'Wins',
'PenaltyShotsSavePCT'		=> 'Penalty Shots Save %',
'Losses'		=> 'Losses',
);

/* End EN Language Pack */
?>