<?php
/* Start FR Language Pack */

$DatabaseNotFound = "La base de donnée n'a pas été trouvé";
$Footer = "Website create by the <a href=\"http://sths.simont.info\">SimonT Hockey Simulator (STHS)</a> pour ";
$WarningResolution = "La résolution de votre navigateur est trop petite pour cette page. Plusieurs informations sont cachées pour garder la page lisible.";

$TableSorterLang = array(
'ShoworHideColumn'		=> 'Afficher ou masquer des colonnes',
'ResetAllSearchFilter'		=> 'Réinitialiser tous les filtres de recherche',
'FilterTips'			=> 'Astuces sur les filtres (Anglais seulement)',
'Search'			=> 'Recherche',
);

$TransactionLang = array(
'LeagueTitle'		=> 'Transactions de Ligue',
'TeamTitle'			=> 'Transactions pour ',
'TradeHistory'			=> 'Historique d\'Échange',
);

$WaiverLang  = array(
'Title'		=> 'Ballotage',
'Waiver'		=> 'Ballotage',
'PlayerName'			=> 'Nom du joueur (Moyenne)',
'FromTeam'			=> 'De l\'équipe',
'Pickedby'			=> 'choisi par',
'DayPutonWaivers'			=> 'Jour placé au ballotage',
'DayRemovedfromWaivers'			=> 'Jour retiré du ballotage',
'WaiverOrder'		=> 'Ordre du ballotage',
);

$CoachesLang = array(
'CoachesTitle'		=> 'Coachs',
'ProCoaches'			=> 'Coachs Pro',
'FarmCoaches'			=> 'Coachs École',
'AvailableCoaches'			=> 'Coachs disponibles',
'CoachesName'			=> 'Nom de l\'entraîneur',
'TeamName'			=> 'Nom de l\'Équipe',
'Age'			=> 'Âge',
'Salary'			=> 'Salaire',
'Contract'			=> 'Contrat',
);

$ScheduleLang = array(
'ScheduleTitle1'		=> 'Ligue ',
'ScheduleTitle2'		=> ' Calendrier',
'TeamTitle'			=> ' Calendrier pour ',
'Day'			=> 'Jour',
'Game'			=> 'Match',
'VisitorTeam'			=> 'Équipe Visiteuse',
'HomeTeam'			=> 'Équipe Locale',
'Score'			=> 'Score',
'Link'			=> 'Lien',
'BoxScore'			=> 'Sommaire du match',
);

$SearchLang = array(
'SearchTitle'		=> 'Recherche',
'Team'		=> 'Équipe:',
'AllTeam'		=> 'Toutes les équipes',
'Type'		=> 'Type:',
'ProandFarm'		=> 'Pro and École',
'ProOnly'		=> 'Pro seulement',
'FarmOnly'		=> 'École seulement',
'OrderField'		=> 'Ordre de champs:',
'Max'		=> 'Max:',
'FreeAgents'		=> 'Agents libres:',
'ThisYear'		=> 'Cette année',
'NextYear'		=> 'L\'année prochaine',
'In2Years'		=> 'Dans 2 ans',
'In3Years'		=> 'Dans 3 ans',
'In4Years'		=> 'Dans 4 ans',
'In5Years'		=> 'Dans 5 ans',
'Unlimited'		=> '0 - Illimité',
'AcsendingOrder'		=> 'Ordre ascendant:',
'DecendingOrder'		=> 'Ordre descendant:',
'Select'		=> 'Selectionner',
'Farm'		=> 'École:',
'PlayersRosterMenu'		=> 'Menu Formation des joueurs',
'GoaliesRosterMenu'		=> 'Menu Formation des gardiens',
'PlayersInformationMenu'		=> 'Menu Informations des joueurs',
'PlayersStatsMenu'		=> 'Menu Statistiques des joueurs',
'GoaliesStatsMenu'		=> 'Menu Statistiques des gardiens',
'TeamStatsMenu'		=> 'Menu Statistiques des équipes',
);

$PlayersLang = array(
'PlayerName'		=> 'Nom du joueur',
'GoalieName'		=> 'Nom du gardien',
'TeamName'			=> 'Nom de l\'équipe',
'Age'			=> 'Âge',
'Birthday'			=> 'Date de naissance',
'Rookie'			=> 'Nouveau joueur',
'Weight'			=> 'Poids',
'Height'			=> 'Taille',
'NoTrade'			=> 'Non-échange',
'ForceWaiver'			=> 'Ballotage  forcé',
'Status'			=> 'Status',
'Contract'			=> 'Contrat',
'Type'			=> 'Type',
'Salary'			=> 'Salaire',
'CurrentSalary'			=> 'Salaire Actuel',
'SalaryYear'			=> 'Salaire Année',
'SalaryRemaining'			=> 'Salaire restant',
'SalaryAverage'			=> 'Salaire moyen',
'SalaryAveRemaining'			=> 'Salaire moyen restant',
'1WayContract'			=> ' (Contrat à 1 volet)',
'OutofPayroll'			=> ' (sur la masse salariale)',
'Link'			=> 'Lien',
'UFA'			=> 'UFA',
'RFA'			=> 'RFA',
);

$DynamicTitleLang = array(
'InDecendingOrderBy'		=> ' en ordre descendant par ',
'InAscendingOrderBy'			=> ' en ordre ascendant par ',
'PlayersInformation'			=> ' Information des joueurs',
'PlayersRoster'			=> ' Formation des Joueurs',
'GoaliesRoster'			=> ' Formation des gardiens',
'GoaliesStat'			=> ' Statistiques des gardiens',
'PlayersStat'			=> ' Statistiques des joueurs',
'TeamStat'			=> ' Statistiques d\'équipe',
'TeamStatVS'			=> ' Statistiques d\'équipe VS',
'PlayersInformation'			=> ' Information des joueurs',
'ThisYearFreeAgents'			=> ' Agents libres cette année',
'NextYearFreeAgents'			=> ' Agents libres l\'année prochaine',
'YearsFreeAgents'			=> ' années agents libres',
'Unassigned'			=> 'Non assigné',
'Pro'			=> ' Pro',
'Farm'			=> ' École',
'All'			=> ' Tous ',
'Top'			=> ' Haut ',
'IndividualLeadersTitle'		=> 'Meneurs individuels',
);

$TeamStatLang = array(
'Overall'		=> 'Ligue',
'Home'			=> 'Domicile',
'Visitor'		=> 'Visiteur',
'TeamName'			=> 'Équipe',
'Last10'		=> 'Dernier 10',
);

$StandingLang = array(
'Standing'		=> ' Classement',
'Wildcard'		=> 'Quatrième As',
'Conference'		=> 'Conférence',
'Division'		=> 'Division',
'Overall'		=> 'Ligue',
);

$TeamLang = array(
'IncorrectTeam'		=> 'Équipe incorrecte',
'Teamnotfound'		=> 'Équipe non trouvée',
'GM'		=> 'DG: ',
'Morale'		=> 'Morale : ',
'TeamOverall'		=> 'Moyenne d\'équipe : ',
'Roster'		=> 'Formation',
'Scoring'		=> 'Points',
'PlayersInfo'		=> 'Informations Joueurs',
'Lines'		=> 'Lignes',
'TeamStats'		=> 'Statistiques d\'équipe',
'Schedule'		=> 'Calendrier',
'Finance'		=> 'Finance',
'Depth'		=> 'Profondeur',
'History'		=> 'Historique',
'InjurySuspension'		=> 'Blessure/Suspension',
'Scratches'		=> 'Rayé',
'TeamAverage'		=> 'MOYENNE D\'ÉQUIPE',
'TotalPlayers'		=> 'Joueurs total',
'AverageAge'		=> 'Âge moyen',
'AverageWeight'		=> 'Poids moyen',
'AverageHeight'		=> 'Taille moyenne',
'AverageContract'		=> 'Contrat moyen',
'AverageYear1Salary'		=> 'Salaire moyen 1ère année',
'LineNumber'		=> 'Ligne #',
'Center'		=> 'Centre',
'LeftWing'		=> 'Ailier Gauche',
'RightWing'		=> 'Ailier Droit',
'Wing'		=> 'Ailier',
'Defense'		=> 'Défense',
'Defenseman'		=> 'Defenseur',
'Goalie'		=> 'Gardien',
'TimePCT'		=> '% Temps',
'PHY'		=> 'PHY',
'DF'		=> 'DF',
'OF'		=> 'OF',
'5vs5Forward'		=> 'Attaque à 5 contre 5',
'5vs5Defense'		=> 'Défense à 5 contre 5',
'PowerPlayForward'		=> 'Attaque en Avantage Numérique',
'PowerPlayDefense'		=> 'Défense en Avantage Numérique',
'PenaltyKill4PlayersForward'		=> 'Attaque à 4 en Désavantage Numérique',
'PenaltyKill4PlayersDefense'		=> 'Défense à 4 en Désavantage Numérique',
'PenaltyKill3Players'		=> '3 joueurs en Désavantage Numérique',
'4vs4Forward'		=> 'Attaque à 4 contre 4',
'4vs4Defense'		=> 'Défense à 4 contre 4',
'LastMinutesOffensive'		=> 'Attaque Dernière minute',
'LastMinutesDefensive'		=> 'Défense Dernière minute',
'ExtraForwards'		=> 'Attaquants Supplémentaires',
'ExtraDefensemen'		=> 'Défenseurs Supplémentaires',
'PenaltyShots'		=> 'Tirs de pénalité',
'CustomOTLinesForwards'		=> 'Lignes d\'attaque perso. en Prol.',
'CustomOTLinesDefensemen'		=> 'Lignes de défense perso. en Prol.',
'Normal'		=> 'Normal',
'PowerPlay'		=> 'Avantage Numérique',
'PenaltyKill'		=> 'Désavantage Numérique',
'DepthChart'		=> 'Charte de profondeur',
'Prospects'		=> 'Éspoirs',
'DraftPicks'		=> 'Choix au repêchage',
'Year'		=> 'Année',
'ArenaCapacityTicketPriceAttendance'		=> 'Arena Capacity - Ticket Price Attendance - %',
'Level'		=> 'Level',
'Luxury'		=> 'Luxury',
'ArenaCapacity'		=> 'Arena Capacity',
'TicketPrice'		=> 'Ticket Price',
'Attendance'		=> 'Attendance',
'AttendancePCT'		=> 'Attendance PCT',
'Income'		=> 'Income',
'HomeGamesLeft'		=> 'Home Games Left',
'AverageAttendancePCT'		=> 'Average Attendance - %',
'AverageIncomeperGame'		=> 'Average Income per Game',
'YeartoDateRevenue'		=> 'Year to Date Revenue',
'ArenaCapacity'		=> 'Arena Capacity',
'TeamPopularity'		=> 'Team Popularity',
'Expenses'		=> 'Expenses',
'PlayersTotalSalaries'		=> 'Players Total Salaries',
'PlayersTotalAverageSalaries'		=> 'Players Total Average Salaries',
'CoachesSalaries'		=> 'Coaches Salaries',
'SpecialSalaryCapValue'		=> 'Special Salary Cap Value',
'YearToDateExpenses'		=> 'Year To Date Expenses',
'SalaryCapPerDays'		=> 'Salary Cap Per Days',
'SalaryCapToDate'		=> 'Salary Cap To Date',
'LuxuryTaxeTotal'		=> 'Luxury Taxe Total',
'Estimate'		=> 'Estimate',
'EstimatedSeasonRevenue'		=> 'Estimated Season Revenue',
'RemainingSeasonDays'		=> 'Remaining Season Days',
'ExpensesPerDays'		=> 'Expenses Per Days',
'EstimatedSeasonExpenses'		=> 'Estimated Season Expenses',
'TeamTotalEstime'		=> 'Team Total Estime',
'EstimatedSeasonExpenses'		=> 'Estimated Season Expenses',
'EstimatedSeasonSalaryCap'		=> 'Estimated Season Salary Cap',
'CurrentBankAccount'		=> 'Current Bank Account',
'ProjectedBankAccount'		=> 'Projected Bank Account',
'OutFor'		=> ' is out for ',
'Restoftheseason'		=> 'the rest of the season ',
'Days'		=> ' days ',
'1Week'		=> '1 week',
'Weeks'		=> 'weeks',
'1Month'		=> '1 month',
'Months'		=> 'months',
'BecauseofFatigue'		=> ' because of a fatigue.',
'Becauseof'		=> ' because of a ',
'SuspendedIndefinitely'		=> ' is suspended indefinitely.',
'SuspendedFor'		=> ' is suspended for ',
'MoresGames'		=> ' mores games.',
'NoInjuryorSuspension'		=> 'No Injury or Suspension.',
'TotalForPlayers'		=> 'Total For Players',
'AllGames'		=> 'All Games',
'HomeGames'		=> 'Home Games',
'VisitorGames'		=> 'Visitor Games',
'Last10Games'		=> 'Last 10 Games',
'PowerPlayAttemps'		=> 'Power Play Attemps',
'PowerPlayGoals'		=> 'Power Play Goals',
'PowerPlayPCT'		=> 'Power Play %',
'PenaltyKillAttemps'		=> 'Penalty Kill Attemps',
'PenaltyKillGoalsAgainst'		=> 'Penalty Kill Goals Against',
'PenaltyKillPCT'		=> 'Penalty Kill %',
'PenaltyKillPCTGoalsFor'		=> 'Penalty Kill Goals For',
'Shots1Period'		=> 'Shots 1 Period',
'Shots2Period'		=> 'Shots 2 Period',
'Shots3Period'		=> 'Shots 3 Period',
'Shots4Period'		=> 'Shots 4+ Period',
'Goals1Period'		=> 'Goals 1 Period',
'Goals2Period'		=> 'Goals 2 Period',
'Goals3Period'		=> 'Goals 3 Period',
'Goals4Period'		=> 'Goals 4+ Period',
'FaceOffs'		=> 'Face Offs',
'WonOffensifZone'		=> 'Won Offensif Zone',
'TotalOffensif'		=> 'Total Offensif',
'WonOffensifPCT'		=> 'Won Offensif %',
'WonDefensifZone'		=> 'Won Defensif Zone',
'TotalDefensif'		=> 'Total Defensif',
'WonDefensifPCT'		=> 'Won Defensif %',
'WonNeutralZone'		=> 'Won Neutral Zone',
'TotalNeutral'		=> 'Total Neutral',
'WonNeutralPCT'		=> 'Won Neutral %',
'PuckTime'		=> 'Puck Time',
'InOffensifZone'		=> 'In Offensif Zone',
'ControlInOffensifZone'		=> 'Control In Offensif Zone',
'InDefensifZone'		=> 'In Defensif Zone',
'ControlInDefensifZone'		=> 'Control In Defensif Zone',
'InNeutralZone'		=> 'In Neutral Zone',
'ControlInNeutralZone'		=> 'Control In Neutral Zone',
);

$IndexLang = array(
'IndexTitle'		=> 'Index',
'LatestScores' 	=> 'Latest Scores',
'LatestTransactions'		=> 'Dernières transactions, blessures, suspensions, ballotages',
'News'		=> ' - Actualité',
'By'		=> ' Par',
'On'		=> ' le',
'Top5Point'		=> ' Top 5 Points',
'Top5Goal'		=> ' Top 5 Buts',
'Top5Goalies'		=> ' Top 5 Gardiens',
'Top20FreeAgents'		=> 'Top 20 Free Agents',
);

$TodayGamesLang = array(
'TodayGamesTitle'		=> ' Matchs du jour',
'BoxScore'		=> 'Sommaire du match',
'ProGames'		=> 'Matchs Pro ',
'FarmGames'		=> 'Matchs École ',
'UnknownGames'		=> 'Matchs inconnus',
);

$GeneralStatLang = array(
'GamePlayed'		=> 'Game Played',
'Points'		=> 'Points',
'Streak'		=> 'Streak',
'Goals'		=> 'Goals',
'Assists'		=> 'Assists',
'ShotsFor'		=> 'Shots For',
'ShotsAgainst'		=> 'Shots Against',
'ShotsBlock'		=> 'Shots Blocked',
'PenaltyMinutes'		=> 'Penalty Minutes',
'Hits'		=> 'Hits',
'EmptyNetGoals'		=> 'Empty Net Goals',
'Shutouts'		=> 'Shutouts',
'Shots'		=> 'Shots',
'ShotsPCT'		=> 'Shots %',
'Pointper20Minutes'		=> 'Point per 20 Minutes',
'FaceoffPCT'		=> 'Face-off %',
'PlusMinus'		=> 'Plus/Minus',
'Rookie'		=> 'Rookie',
'PowerPlayGoals'		=> 'Power Play Goals',
'ShortHandedGoals'		=> 'Short Handed Goals',
'GameWinningGoals'		=> 'Game Winning Goals',
'GameTyingGoals'		=> 'Game Tying Goals',
'MinutesPlayed'		=> 'Minutes Played',
'HatTricks'		=> 'Hat Tricks',
'GoalsScoringStreak'		=> 'Goals Scoring Streak',
'PointsScoringStreak'		=> 'Points Scoring Streak',
'HitsReceived'		=> 'Hits Received',
'PenaltyShotsGoals'		=> 'Penalty Shots Goals',
'GiveAways'		=> 'Give Aways',
'TakeAways'		=> 'Take Aways',
'TotalFight'		=> 'Total Fight',
'FightWon'		=> 'Fight Won',
'SavePCT'		=> 'Save Percentage',
'GoalsAgainstAverage'		=> 'Goals Against Average',
'Wins'		=> 'Wins',
'PenaltyShotsSavePCT'		=> 'Penalty Shots Save %',
'Losses'		=> 'Losses',
);

 /* End FR Language Pack */
?>